### ISSUE TITLE
Not an editor command: GComponent my-component

### ISSUE THREAD

**Issue by CheesePizza100** [bdauria/angular-cli.vim#13]
Environment:
Windows 7
gVim 8.0

Steps to reproduce:
Open gVim
cd to project directory (cd c:\projects\angular\tour-of-heroes)
:Component foo-bar

Outcome:
Not an editor command: GComponent foo-bar

Snippet from _vimrc:
call plug#begin('C:/Program Files (x86)/Vim/vimfiles/.vim/plugged')
Plug 'https://github.com/bdauria/angular-cli.vim'
call plug#end()

I expected a component to be generated. What I did find interesting is this worked:
Open command prompt
cd to directory of project (cd c:\projects\angular\tour-of-heroes)
now at the command prompt, open vim
now in vim :GComponent foo-bar

**Comment by bdauria** [comment]
Did you load the plugin using an autocmd ? In that case, you are probably checking if an angular component is available while opening Vim, which is not the case when you do so outside your project hence not loading the plugin. 

You probably want to be less restrictive by loading the plugin, either by loading it when Vim loads (by putting `call angular_cli#init()` somewhere in your .vimrc) or by filetype (`autocmd FileType typescript,html call angular_cli#init()`).

**Comment by CheesePizza100** [comment]
Yeah in my _vimrc I have this:

autocmd VimEnter * if globpath('.,..','node_modules/@angular') != '' | call angular_cli#init() | endif

After battling with this for far too long, I think it has nothing to do with your plugin and it is a set up issue/path issue. What I mean by that is when Vim starts up, it scans certain drives right? When I check rtp it looks in several directories, including H. And the H directory is a corporate network drive. On a side note, angular-cli vim works right out of the box on my home machine :)

I think this can be closed. Ultimately I have it working by using tpope's vim-dispatch.
