### ISSUE TITLE
Command Namespace cluttered.

### ISSUE THREAD

**Issue by lgalke** [bdauria/angular-cli.vim#3]
Hello @bdauria,

I appreciate your work on making the angular-cli available in vim.
One issue I experienced is that the commands are defined unconditionally in `plugin/*`.
Thus, indendent of file-type or project I am working in, my command namespace is cluttered with:
EComponent, EDirective, EModule, ENg, EPipe, EService, ESpec, EStylesheet, ..., ..., Ng.

I agree that the commands should be available over several filetypes: `html`, `ts`, probably also `js`.

I am quite new to angular development, but I would assume that there is at least one project file which could be used as an indicator that we are currently inside an angular project.

So I suggest
- move command definitions inside `autoload/*`
and then either
- invoke on a set of specific filetypes `ftplugin/*`, such as `ts` and `html`.
- check for existence of some angular specific file in the project root.
- Expose a function call like `angular_cli#define_commands()` which can called by users in autocmds (quick win solution)

What's your opinion?

Best Regards,
lgalke

**Comment by bdauria** [comment]
Hey @lgalke,

Thanks for your feedback. You're right, the plugin should be loaded for the specific filetypes it targets only. Regarding the angular specific files to look at, do you have something specific in minds? I think it's important to stay a bit flexible on this. For instance, I mainly use the plugin for NativeScript @Angular2 projects and not only for angular-cli. 

autocommands are a good idea as well.

**Comment by lgalke** [comment]
Since I am quite new to angular, I am not sure whether there is some safe way, to check for the presence of an angular project just by the files (except for probably looking up node_modules) but that feels cumbersome. As you pointed out, the exact file types also differ. Thus I would suggest to go with just exposing a single function to set up the commands. It would be the most flexible and powerful option: everyone can define his own rule for when to define the commands.

**Comment by lgalke** [comment]
[PR](https://github.com/bdauria/angular-cli.vim/pull/4)

**Comment by bdauria** [comment]
The PR has been merged. It looks good to me. I've just corrected the call of GetNgSourceExtension() where the angular_cli# prefix was missing. 

I'll close the issue as soon as the README has been updated according to the changes. 

Thanks again for this.

**Comment by lgalke** [comment]
[Here you are](https://github.com/bdauria/angular-cli.vim/pull/5)

**Comment by bdauria** [comment]
Excellent. I'm closing this. Thanks for your contribution @lgalke
